# Generated by Django 5.1.6 on 2025-03-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='default_user', max_length=150, null=True, unique=True),
        ),
    ]
